### ISSUE TITLE
Finish docu first

### ISSUE THREAD

**Issue by buhtz** [oz123/man-utils#2]
I found your package on StackOverflow and find it interesting.
But you have nearly no documentation. Please finish the docu ASAP to make it easier for possible contributors to decide if they participate or not.

I'm interested but won't invest my spare time in reading code just to understand what your package really is doing.

**Comment by oz123** [comment]
This project is pretty much dead. There are similar projects in pypi that do similar stuff.
If you want to see how this project is used check out https://github.com/pwman3/pwman3.
This project was developed there initially.

**Comment by buhtz** [comment]
Then please mention the current project status in the beginning of your README file please.

I also would recommend to remove the empty documentation from ReadTheDocs to save their resources.

**Comment by oz123** [comment]
Danke aber nein danke.
